### ISSUE TITLE
Not loading on Build 3112

### ISSUE THREAD

**Issue by nfantone** [SublimeLinter/SublimeLinter-tslint#9]
Plugin fails initialisation when booting up Sublime. Console shows:

``` sh
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/nfantone/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-tslint/linter.py", line 16, in <module>
    class Tslint(Linter):
  File "/Users/nfantone/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 75, in __init__
    if isinstance(syntax, str) and syntax[0] == '^':
IndexError: string index out of range
```

Also, shouldn't this linter be a subclass of [NodeLinter](https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/node_linter.py)?

**Comment by nfantone** [comment]
I've noticed that my `linter.py` file was completely different from the one in the repo, filled with default values for each attribute in the class. I replaced its contents with what I found here and it started working.

Any ideas of what could have happened?

**Comment by clementprevot** [comment]
Same here, it seems that the package installed via Package Control is not correct.

The definition of `build_args` is missing. Fixing the linter.py file fixes the linter in sublime

**Comment by braver** [comment]
It's been a while, whatever was wrong is now probably fixed.
